services:
  - type: web
    name: weatherpro-backend
    runtime: node
    rootDirectory: backend/
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000

  - type: static_site
    name: weatherpro-frontend
    buildCommand: npm run build
    publish: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://weatherpro-backend.onrender.com